name: Scaffold Pkg PR
description: Action for creating a pull request with scaffolded package contents based off a comment.
author: Philipp Burckhardt <pburckhardt@outlook.com>

inputs:
  OPENAI_API_KEY:
    description: Your OpenAI API key for the GPT-3 API.
    required: true

runs:
  using: node12
  main: dist/index.js

branding:
  icon: box
  color: green