name: Scaffold Pkg PR
description: Action for scaffolding a new `stdlib` package via GPT-3.
author: Philipp Burckhardt <pburckhardt@outlook.com>

inputs:
  OPENAI_API_KEY:
    description: Your OpenAI API key for the GPT-3 API.
    required: true
  GITHUB_TOKEN:
    description: Your GitHub token for interacting with the GitHub API.
    required: true
  pkg:
    description: The package path.
    required: false
  type:
    description: Scaffold action type (e.g., `native-addon`).
    required: false

runs:
  using: node16
  main: dist/index.js

branding:
  icon: box
  color: green